baseURL = 'https://saugatp.github.io'
languageCode = 'en-gb'
title = 'Saugat Poudel'
author = "Steve Francia"
copyright = "Copyright © 2024, Saugat Poudel; all rights reserved."
paginate = 4
theme = 'paper'
enableEmoji = false
canonifyURLs = true

[params]
  color = 'light'
  twitter = 'real.gamedev'
  github = 'saugatp'
  instagram = 'real.saugat'
  rss = true
  name = 'Welcome!'
  bio = 'I am a student currently at Northumbria University. I am interested in Data analysis and research, however I also have a solid background in mobile apps development. Good to see you here 😀'
  avatar = 'poudelsaugat45@gmail.com'
  disablePostNavigation = true
  monoDarkIcon = true 
  math = true
  
[menu]
  [[menu.main]]
    identifier = "Journals"
    name = "Journals"
    url = "/journals/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
