baseURL = "https://saugatp.github.io"
languageCode = "en-gb"
title = "Saugat Poudel - Software Developer | Student"
author = "Saugat Poudel"
copyright = "Copyright © 2024, Saugat Poudel; all rights reserved."
description = "I am Saugat Poudel. I share my thoughts, insights, and experiences on data analysis, research, and my journey of mobile app development in this blog."
paginate = 4
theme = 'paper'
enableEmoji = false
canonifyURLs = true

[services]
  [services.googleAnalytics]
    ID = 'G-15TZEHL3PN'

[params]
  color = 'light'
  github = 'saugatp'
  instagram = 'real.saugat'
  rss = true
  name = "Hey there, i'm saugat."
  bio = 'read my latest blogs below...'
  disablePostNavigation = true
  monoDarkIcon = true 
  math = false
  
[menu]
  [[menu.main]]
    identifier = "Journals"
    name = "Journals"
    url = "/journals/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
