baseURL = 'https://saugatp.github.io/portfolio'
languageCode = 'en-gb'
title = 'Saugat Poudel'
theme = 'paper'
enableEmoji = true
canonifyURLs = true

[params]
  color = 'linen'
  twitter = 'real.gamedev'
  github = 'saugatp'
  instagram = 'real.saugat'
  rss = true
  name = 'Welcome!'
  bio = 'I am a student currently at Northumbria University. I am interested in Data analysis and research, however I also have a solid background in mobile apps development. Good to see you here 😀'
  avatar = 'poudelsaugat45@gmail.com'
  disablePostNavigation = true
  monoDarkIcon = true 
  math = true
[menu]
  [[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    identifier = "journal"
    name = "Journal"
    url = "/live"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
