baseURL = "https://saugatp.github.io"
languageCode = "en-gb"
title = "Saugat Poudel | Software Developer, Student"
author = "Saugat Poudel"
copyright = "Copyright © 2024, Saugat Poudel; all rights reserved."
description = "I'm Saugat Poudel. Here, I share my thoughts, insights, and experiences on data analysis, research, and my journey of mobile app development. Whether you're a fellow student, tech enthusiast, or just curious, join me as we explore the fascinating intersections of technology and creativity."
paginate = 4
theme = 'paper'
enableEmoji = false
canonifyURLs = true

[params]
  color = 'light'
  twitter = 'real.gamedev'
  github = 'saugatp'
  instagram = 'real.saugat'
  rss = true
  name = 'Welcome!'
  bio = 'to my personal thoughts...'
  disablePostNavigation = true
  monoDarkIcon = true 
  math = true
  
[menu]
  [[menu.main]]
    identifier = "Journals"
    name = "Journals"
    url = "/journals/"
    weight = 1

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
